Repository lylykvvl/mouse_car, pull requests merged in 2022-04, with the labels that each got.

#1 M-1-Projeck_sceleton
  images/car_0.jpg
  images/car_1.jpg
  images/car_10.jpg
  images/car_11.jpg
  images/car_12.jpg
  images/car_13.jpg
  images/car_14.jpg
  images/car_15.jpg
  images/car_16.jpg
  images/car_17.jpg
  images/car_18.jpg
  images/car_19.jpg
  images/car_2.jpg
  images/car_20.jpg
  images/car_21.jpg
  images/car_3.jpg
  images/car_4.jpg
  images/car_5.jpg
  images/car_6.jpg
  images/car_7.jpg
  images/car_8.jpg
  images/car_9.jpg
  images/facebook.png
  images/header.jpg
  images/instagram.png
  images/logo_footer.png
  images/logo_header.png
  images/minus_icon.png
  images/more.png
  images/new.png
  images/plus_icon.png
  images/shape.png
  images/shape_desabled.png
  images/sort_car.png
  index.html
  style/style.css
  style/style.css.map
  style/style.scss
Labels: good first issue

#3 M-3-Reverse_date
  images/car_0.jpg
  images/car_1.jpg
  images/car_10.jpg
  images/car_11.jpg
  images/car_12.jpg
  images/car_13.jpg
  images/car_14.jpg
  images/car_15.jpg
  images/car_16.jpg
  images/car_17.jpg
  images/car_18.jpg
  images/car_19.jpg
  images/car_2.jpg
  images/car_20.jpg
  images/car_21.jpg
  images/car_3.jpg
  images/car_4.jpg
  images/car_5.jpg
  images/car_6.jpg
  images/car_7.jpg
  images/car_8.jpg
  images/car_9.jpg
  images/facebook.png
  images/header.jpg
  images/instagram.png
  images/logo_footer.png
  images/logo_header.png
  images/minus_icon.png
  images/more.png
  images/new.png
  images/plus_icon.png
  images/shape.png
  images/shape_desabled.png
  images/sort_car.png
  index.html
Labels: duplicate

#2 M-2-Changed_date
  index.html
Labels: bug

#5 M-5 Readme changes
  README.md
Labels: help wanted
